name: test work1
on:
  workflow_dispatch:
jobs:
  test1:
    runs-on: windows-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install latest Google Chrome
        run: |
          $localPath = "$env:TEMP\googlechrome_installer.exe"
          Invoke-WebRequest -Uri "https://dl.google.com/chrome/install/latest/googlechromestandaloneenterprise64.msi" -OutFile $localPath
          Start-Process -FilePath msiexec.exe -ArgumentList "/i", $localPath, "/quiet", "/norestart" -NoNewWindow -Wait
        shell: pwsh

      - name: Run test
        run: behave Behave_Mojo\features\login.feature
