name: test work1
on:
  workflow_dispatch:
jobs:
  test1:
    runs-on: windows-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3

      - name: Install latest Google Chrome
        run: |
          $Path = "$env:TEMP\chrome_installer.exe"
          Invoke-WebRequest -Uri "https://dl.google.com/chrome/install/latest/chrome_installer.exe" -OutFile $Path
          Start-Process -FilePath $Path -ArgumentList "/silent", "/install" -NoNewWindow -Wait
        shell: pwsh
        
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run test
        run: behave Behave_Mojo\features\login.feature


